[project]
name = "m-ifeval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "polars>=1.29.0",
    "typed-argument-parser>=1.10.1",
    "vllm>=0.8.5.post1",
]
